function data = basicTestsData()
data = struct('basicOperators',{1},'basicTests',{1},'needTol',{1}, ...
        'maxMatrixSize', {1}, 'relativeTol', {1});

data.maxMatrixSize = 100;
data.relativeTol = 1e-14;

data.basicOperators = {'Eye', 'Dirac', 'Zeros', 'Ones', 'Diag', 'DCT', ...
    'FFT', 'Haar', 'Hadamard', 'Heaviside', 'Toeplitz', 'ToepGauss', ...
    'ToepSign'};
                   %only checking if these methods are implemented
data.basicTests = {'Full', 'Double', ...
                ...%simple checks for these methods
                   'Char', ... 
                ...%simple checks that rely on double
                   'VectProd', 'Transpose', 'IsEmpty', 'IsReal', 'IsScalar',... 
                   'NDims', 'NormEst', 'Size', 'Conj', 'CTranspose', 'Diag'};

% data.basicOperators = {'Eye', 'Dirac', 'Zeros', 'Ones', 'Diag', 'DCT', ...
%     'Hadamard', 'Heaviside', 'ToepGauss', ...
%     'ToepSign'};
% data.basicTests = {'Char', 'VectProd'};
end