function lists = opsBasic
lists = struct('basicOperators',{1},'basicTests',{1},'tol',{1});

% lists.basicOperators = {'Eye', 'Dirac', 'Zeros', 'Ones', 'Diag', 'DCT', ...
%     'FFT', 'Haar', 'Hadamard', 'Heaviside', 'Toeplitz', 'ToepGauss', ...
%     'ToepSign'};
lists.basicTests = {'VectProd',     'Double',           'Char',         'Transpose'...
                    'Full',         'IsEmpty',          'IsReal',       'IsScalar',...
                    'NDims',        'NormEst',          'Size',         'Conj',...
                    'CTranspose',   'Diag'};
lists.tol     =    [ true,           true,               false,          true,...
                     false,          false,              false,          false,...
                     false,          true,               false,          false,...
                     true,           false];

lists.basicOperators = {'Eye', 'Dirac', 'Zeros', 'Ones', 'Diag', 'DCT', ...
    'Hadamard', 'Heaviside', 'ToepGauss', ...
    'ToepSign'};
% lists.basicTests = {'Conj', 'CTranspose'};
% lists.tol = [false, true];
end