function test_real
%test_real  Unit tests for real method

   seed = randn('state');
   
   % Set up matrices and operators for problems
   A  = randn(2,2) + sqrt(-1) * randn(2,2);
   B  = opMatrix(A);
   c  = randn(1,1) + sqrt(-1) * randn(1,1);
   A  = A * c;
   B  = B * c;
   xr = randn(2,2);
   xi = sqrt(-1) * randn(2,2);
   x  = xr + xi;

   % Check operator products
   assertElementsAlmostEqual( ...
       real(A)*x   ,...
       real(B)*x   );
   assertElementsAlmostEqual( ...
       real(A)*xr  ,...
       real(B)*xr  );
   assertElementsAlmostEqual( ...
       real(A)*xi  ,...
       real(B)*xi  );
   assertElementsAlmostEqual( ...
       real(A)'*x  ,...
       real(B)'*x  );
   assertElementsAlmostEqual( ...
       real(A)'*xr  ,...
       real(B)'*xr  );
   assertElementsAlmostEqual( ...
       real(A)'*xi  ,...
       real(B)'*xi  );
   assertElementsAlmostEqual( ...
       real(A')*x  ,...
       real(B')*x  );
   assertElementsAlmostEqual( ...
       real(A')*xr  ,...
       real(B')*xr  );
   assertElementsAlmostEqual( ...
       real(A')*xi  ,...
       real(B')*xi  );
   
end
