function test_transpose
%test_transpose  Unit tests for operator transpose

   randn('state',0); rand('state',0);
   
   % Set up matrices and operators for problems
   A  = randn(2,2) + sqrt(-1) * randn(2,2);
   B  = opMatrix(A);
   c  = randn(1,1) + sqrt(-1) * randn(1,1);
   A  = A * c;
   B  = B * c;
   xr = randn(2,2);
   xi = sqrt(-1) * randn(2,2);
   x  = xr + xi;

   % Check operator products
   C = A' * 5 * A;
   D = B' * 5 * B;
   assertElementsAlmostEqual( ...
       ((5*A*C)' * A) * x    ,...
       ((5*B*D)' * B) * x     );
   assertElementsAlmostEqual( ...
       ((5*A*C)' * A) * xr'  ,...
       ((5*B*D)' * B) * xr'   );
   assertElementsAlmostEqual( ...
       ((5*A*C)' * A) * xi'  ,...
       ((5*B*D)' * B) * xi'   );
   assertElementsAlmostEqual( ...
       (5*A*C*A) * x         ,...
       (5*B*D*B) * x          );
   assertElementsAlmostEqual( ...
       (5*A*C*A) * xr        ,...
       (5*B*D*B) * xr         );
   assertElementsAlmostEqual( ...
       (5*A*C*A) * xi        ,...
       (5*B*D*B) * xi         );

end
